# Рівновага Неша в домінуючих стратегіях. Алгоритми її обчислення.

## Ігри в нормальній формі

Теорія ігор досліджує інтерактивне прийняття рішень.

---

Гра \\(N\\) учасників в стратегічній формі містить:

- Скінченну множину гравців $N$
- Простори стратегій для кожного гравця: $\{S_1,S_2,S_3,\dots,S_N\}$;
- Функції виграшу для кожного гравця: $u_i:S_1\times S_2\dots\times S_N\to\mathbb{R}$

Якщо гра однокрокова, то виграші зручно задавати матрицями. А - виграші першого гравця, В - матриця другого гравця. 

- Матричні ігри - цн ігри, де А = -В
- Біматричні - всі інші. 

In [34]:
import numpy as np
A = np.array([[1, 2, 2], [4, 4, 2], [2, 3, 1]])
B = np.array([[2, 1, 1], [2, -1, -2], [3, 2, -1]])
A

array([[1, 2, 2],
       [4, 4, 2],
       [2, 3, 1]])

In [35]:
B

array([[ 2,  1,  1],
       [ 2, -1, -2],
       [ 3,  2, -1]])

Розглянемо наступну гру:

> Пара вирішує, що вони хочуть дивитись спорт чи комедію. Алісі більше подобається комедія, а Боб любить спорт. Важливо, що вони більш цінують перегляд ТВ разом ніж окремо.

Для представлення математично цієї стратегічної ситуації ми призначимо **корисності** кожній з чотирьох можливих ситуацій:

1. Аліса дивиться спорт, Боб дивиться комедію: Аліса і Боб отримують $0$.
2. Аліса дивиться комедію, Боб дивиться спорт: Аліса і Боб отримують $0$.
3. Аліса і Боб дивляться спорт: Аліса отримує $3$, Боб отримує $2$.
4. Аліса і Боб дивляться комедію: Аліса отримує $2$, Боб отримує $3$.

Ця гра отримала назву "Сімейна сварка" ("battle of the sexes", "bach or stravinsky" ) і ми її представимо у вигляді двох матриць, $A$ - це виграші Аліси:

$$
A = 
\begin{pmatrix}
3 & 0\\
0 & 2
\end{pmatrix}
$$

а матриця $B$ представляє виграші Боба:

$$
B = 
\begin{pmatrix}
2 & 0\\
0 & 3
\end{pmatrix}
$$

За домовленістю **Аліса вибирає рядки** а **Боб вибирає стовпці**: 

Це представлення називається **Грою в нормальній (стратегічній) формі**.

Для гри сімейна сварка:

- У нас двоє гравців (Аліса і Боб) 
- Простори стратегій : $S_1=S_2=\{\text{комедія}, \text{спорт}\}$ або еквівалентно $S_1=S_2=\{1, 2\}$
- Функції виграшу відображують елемент декартової множини просторів стратегій $\tilde s \in S_1\times S_2=\{(1, 1), (1, 2), (2, 1), (2, 2)\}$ в $\mathbb{R}$:

   $$u_1(\tilde s)=A_{\tilde s},$$
   
   $$u_2(\tilde s)=B_{\tilde s}.$$
   
---

# Раціоналізація

## Визначення строго домінованої стратегії


В біматричній грі $(A, B)\in\mathbb{{R^{m \times n}}^2}$ стратегія $s$ називається _домінуючою_ стратегією, якщо для будь-якої іншої стратегії $\bar s$ та для всіх стратегій іншого гравця $t$:

$$
u(s, t) > u(\bar s, t)
$$


слабо домінуючою, якщо знак $\ge$ 

In [36]:
# Задача - написати алгоритм пошуку строго домінуючої стратегії


# для В

(all(B[:,0] > B[:,1]) and all (B[:,0] > B[:,2])) or (all(B[:,1] > B[:,0]) and all(B[:,1] < B[:,2])) or (all(B[:,2] > B[:,0]) and all(B[:,0] < B[:,1]))

# Давайте напишемо загальну функцію для А та В

True

In [27]:
import numpy as np
A = np.array([[3, 0], [3, 1]])
B = np.array([[3, 3], [0, 1]])

In [29]:
A

array([[3, 0],
       [3, 1]])

In [30]:
B

array([[3, 3],
       [0, 1]])

In [31]:
# Перевіримо, що перший рядок слабо домінований другим
all(A[0,:] <= A[1,:]) and any(A[0,:] < A[1,:])

True

In [32]:
# Перевіримо, що перший стовпець слабо домінований другим
all(B[:,0] <= B[:,1]) and any(B[:,0] < B[:,1])

True

## Приклади рівноваги в домінуючих стратегіях

### Ринок реклами табачних компаній

Є дві стратегії - рекламувати і не рекламувати. Припустимо є ринок ємністю 100.
Витрати на рекламу х, той, хто рекламує - забирає 2/3 ринку, якщо реклами іншого немає. Якщо рекламуються обоє, то вони ділять ринок приблизно порівну.

$$
M = 
\begin{pmatrix}
50 - х, 50 - х & 66 - х, 33 \\
33, 66 - х & 50, 50
\end{pmatrix}
$$

Завдання. Проаналізувати можливі рівноваги в залежності від х.


## Визначення домінованої стратегії


В біматричній грі $(A, B)\in\mathbb{{R^{m \times n}}^2}$ стратегія $s$ називається _домінованою_ стратегією  $\bar s$, якщо для всіх стратегій іншого гравця $t$:

$$
u(s, t) < u(\bar s, t)
$$

---

Зокрема розглянемо дилему ув'язненого:

$$
A =
\begin{pmatrix}
    3 & 0\\
    5 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    3 & 5\\
    0 & 1
\end{pmatrix}
$$

- можна побачити, що $A_{2j} > A_{1j}$ для всіх $j$, отже перша стратегія першого гравця домінована по відношенню до другої.
- можна побачити, що $B_{i2} > B_{i1}$ для всіх $i$, отже перша стратегія другого гравця домінована по відношенню до другої.

---

## Слабо доміновані стратегії


В біматричній грі $(A, B)\in\mathbb{{R^{m \times n}}^2}$ стратегія $s$ називається _слабо домінованою_ стратегією  $\bar s$, якщо для всіх стратегій іншого гравця $t$:

$$
u(s, t) \leq u(\bar s, t)
$$

**та існує ** стратегія $t'$ така, що:

$$
u(s, t') < u(\bar s, t')
$$

---

Наприклад, розглянемо модифіковану версію попередньої гри:

$$
A =
\begin{pmatrix}
    3 & 0\\
    3 & 1
\end{pmatrix}\qquad
B =
\begin{pmatrix}
    3 & 3\\
    0 & 1
\end{pmatrix}
$$

- видно, що $A_{2j} \geq A_{1j}$ для всіх $j$ **і** $A_{22} > A_{12}$, отже перша стратегія слабо домінована другою.
- видно, що $B_{i2} \geq B_{i1}$ для всіх $i$ **і** $B_{22} > B_{21}$, отже перша стратегія слабо домінована другою.

Перевіримо умови домінування

## Задача 1. 

Побудувати алгоритм видалення домінованих (слабо домінованих) стратегій та визначає рівновагу у домінуючих стратегіях в результуючій грі.  

## Задача 2. 

Припустимо ми генеруємо дві випадкові матриці 2х2 зі значеннями -1, 0, 1. Яка ймовірність того, що в грі
а) буде рівновага в домінуючих стратегіях.
б) буде рівновага при ітераційному видаленні домінованих стратегій. 

## Задача 3. Аукціон

На аукціоні продається лот, який ви оцінюєте в 400. Ваш суперник оцінює лот в 300. За умовами аукціону крок оголошення ставки 100. Припустимо, що спочатку ми розглядаємо аукціона з першою ціною - тобто переможець отримує лот, та платить свою ставку. Якщо ставки однакові - аукціонер підкидає монетку.
1. Визначити матрицю та знайти рівновагу за допомогою видалення домінованих стратегій.
2. Розглянути аукціон з другою ціною. Як це змінює рівновагу?